#!/usr/bin/env ruby

# Build/Compile the application
#
# 1 - Run boxfile.yml before_build
# 2 - Run engine build script
# 3 - Run boxfile.yml after_build

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

# import some logic/helpers from lib/*.rb
include Nanobox::Engine
include Nanobox::Output