#!/usr/bin/env ruby

# Enable an app to remove unecessary binaries from the deployed environment

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

# import some logic/helpers from lib/*.rb
include Nanobox::Engine
include Nanobox::Output
include Nanobox::Boxfile

# 1 - Run engine clean script
logger.print(bullet("Running clean hook..."), 'debug')

if ::File.exist? "#{ENGINE_DIR}/bin/cleanup"

  logger.print(bullet("Cleanup script detected, running now..."), 'debug')

  execute "cleanup build" do
    command %Q(stdbuf -o0 #{ENGINE_DIR}/bin/cleanup '#{engine_payload}')
    cwd "#{ENGINE_DIR}/bin"
    path GONANO_PATH
    environment engine_env
    user 'gonano'
    stream true
    on_data {|data| logger.print(data)}
  end
end

# 2 - Remove orphan pkgsrc dependencies
logger.print(process_start("Removing orphaned packages"))

execute "autoremove pkgin orphans" do
  command <<-EOF
    siphon --prefix '   ' -- \
      bash -c "echo \"Y\\n\" | pkgin ar"
  EOF
  path GONANO_PATH
  stream true
  on_data {|data| logger.print data }
end
