#!/usr/bin/env ruby

# Enable an app to remove unecessary binaries from the deployed environment

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

# 1 - Run engine clean script
logger.print(bullet("Running clean hook..."), 'debug')

if ::File.exist? "#{ENGINE_DIR}/#{registry('engine')}/bin/clean"

  logger.print(bullet("Cleanup script detected, running now..."), 'debug')

  execute "cleanup build" do
    command %Q(#{ENGINE_DIR}/#{registry('engine')}/bin/cleanup '#{engine_payload}')
    cwd "#{ENGINE_DIR}/#{registry('engine')}/bin"
    path GONANO_PATH
    user 'gonano'
    stream true
    on_data {|data| logger.print data}
  end
end
