#!/usr/bin/env ruby

# Upload build env and live app to warehouse
# 1 - Verify build and app exist
# 2 - upload to warehouse

# how to show progress during an rsync transfer:
# http://www.cyberciti.biz/faq/show-progress-during-file-transfer/

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

# import some logic/helpers from lib/*.rb
include Nanobox::Engine
include Nanobox::Output
include Nanobox::Boxfile

# 1 - verify

# 2 - upload to warehouse
#
# 2a - if previous build is set, we use slurp
# 2b - if previous build is not set, we upload to warehouse directly
#
if payload[:previous_build] and not payload[:previous_build].empty?

  { 'app' => APP_DIR, 'deploy' => DEPLOY_DIR }.each_pair do |part, dir|

    previous = "#{part}-#{payload[:previous_build]}.tgz"
    current  = "#{part}-#{payload[:build]}.tgz"

    prefix = ""
    if part == 'deploy'
      prefix = "Syncing runtime"
    else
      prefix = "Syncing app"
    end

    logger.print(bullet("#{prefix}..."))

    if part == 'deploy'
      logger.print(bullet("Extracting runtime from previous deploy..."))
    else
      logger.print(bullet("Extracting app from previous deploy..."))
    end
    
    # register a stage with slurp
    execute "create stage for #{part}" do
      command "siphon --prefix '  ' -- curl \
            -k \
            -f \
            -o /dev/null \
            -H 'X-AUTH-TOKEN: #{payload[:warehouse_token]}' \
            -d '{\"old-id\": \"#{previous}\", \"new-id\": \"#{current}\"}' \
            https://#{payload[:warehouse]}:1566/stages"
    end

    # sync
    execute "sync #{part}" do
      command <<-EOF
        siphon --prefix '   #{prefix}: ' -- bash -c "\
          rsync \
            -a \
            -v \
            --delete \
            . \
            -e 'ssh -p 1567' \
            #{current}@#{payload[:warehouse]}:#{current}"
      EOF
      user 'gonano'
      cwd dir
      stream true
      on_data { |data| logger.print data }
    end

    if part == 'deploy'
      logger.print(bullet("Committing runtime..."))
    else
      logger.print(bullet("Committing app..."))
    end

    # commit to warehouse
    execute "commit #{part} stage" do
      command "siphon --prefix '  ' -- curl \
            -k \
            -f \
            --progress-bar \
            -o /dev/null \
            -H 'X-AUTH-TOKEN: #{payload[:warehouse_token]}' \
            -X PUT \
            https://#{payload[:warehouse]}:1566/stages/#{current}"
    end

  end

else

  # While we could pipe the output of tar directly into curl, curl
  # can't provide a progress bar since the data is streaming and the size
  # is unknown. So we'll be slightly less optimal here in trade of visibility

  { 'app' => APP_DIR, 'deploy' => DEPLOY_DIR }.each_pair do |part, dir|

    prefix = ""
    if part == 'deploy'
      prefix = "Sending runtime"
    else
      prefix = "Sending app"
    end

    logger.print(bullet("#{prefix}..."))

    if part == 'deploy'
      logger.print(bullet("Generating compressed tarball of runtime..."))
    else
      logger.print(bullet("Generating compressed tarball of app..."))
    end

    execute "create #{part} tarball" do
      command <<-EOF
        siphon --prefix '  ' -- bash -c "\
          tar -cf - . \
            | pv \
              -s $(du -sb #{dir} | awk '{print $1}') \
                | gzip \
                  > /var/tmp/#{part}-#{payload[:build]}.tgz"
      EOF
      cwd dir
    end

    execute "publish deploy" do
      command "siphon --prefix '  #{prefix}: ' -- curl \
            -k \
            -f \
            --progress-bar \
            -o /dev/null \
            -H 'x-auth-token: #{payload[:warehouse_token]}' \
            --data-binary @/var/tmp/#{part}-#{payload[:build]}.tgz \
            https://#{payload[:warehouse]}:7410/blobs/#{part}-#{payload[:build]}.tgz"
      stream true
      on_data { |data| logger.print data }
    end

  end
end
