#!/bin/bash

# 1) create a digest of the /data pkgsrc bootstrap
find /data | sed 's/\/data//;s/\[/\\\[/' > /var/nanobox/build-excludes.txt

# 2) parse the list of exceptions and remove any matching entries
for entry in $(cat /var/nanobox/build-exceptions.txt | grep -v '#'); do
  echo "excluding: $entry"
  rule=$(echo $entry | sed 's/\//\\\//g')
  sed -i "/${rule}/d" /var/nanobox/build-excludes.txt
done

# 3) Exclude the user's ssh folder to prevent it from being published to production servers
echo "/var/home/gonano/.ssh" >> /var/nanobox/build-excludes.txt